name: Maven Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Call Deploy Workflow
    if: github.event_name != 'pull_request'
    uses: doytowin/doyto-devops/.github/workflows/deploy.yml@main
    secrets: inherit
